### ISSUE TITLE
Mobile version layout

### ISSUE THREAD

**Issue by adamgstudio** [organised/gkits#11]
The page looks good but it’s all off-centre, can we fix?

**Comment by organised** [comment]
keeping this here for future reference so I can file an actual bug report for construct. 

when you export and you have a custom style sheet, or even when you don't have one, you get a subpar embed page, that is in many ways inferior to the one used in the remote preview. 

anyway I stole this code below from the remote preview and added it in to the mobile version, I suspect it'll do wonders for the desktop version too. result is that now we have margins fixed. but it'll break again the moment i hit export. I've added this to the user style.css inside the interactive resource.

```

/* remove padding, margin and any touch action or delay */
html, body {
	padding: 0;
	margin: 0;
	overflow: hidden;
	
	background: white;		/* overridden by JS in preview mode */
	color: white;
}

input, button, select {
	padding: 0;
	margin: 0;
}

html, body, canvas {
	touch-action-delay: none;
	touch-action: none;
}
```
