### ISSUE TITLE
desktop save

### ISSUE THREAD

**Issue by adamgstudio** [organised/gkits#19]
any chance the file that downloads when you hit SAVE on desktop, can be square?

**Comment by adamgstudio** [comment]
OR - the grammar logo/address in moved right so when the user puts on instagram it will be ok for square crops?

**Comment by organised** [comment]
No one saves the image from desktop to put on Instagram though right? 

They can screenshot the mobile and it fits in nice for Instagram. Do you want to reposition the label on desktop at all?

**Comment by organised** [comment]
Also can’t squareify the image, it’s a snapshot of the canvas element in its entirety sadly

**Comment by adamgstudio** [comment]
I suppose, it’s a bit of a long way round. Let’s just leave it
