### ISSUE TITLE
Dotted line after titles

### ISSUE THREAD

**Issue by adamgstudio** [organised/gkits#2]
All lines need to be same position and inline with title text, and gap needs to be same. SWATCH, MASKSA & EDITOR look to be correct

**Comment by organised** [comment]
Done! within the limitations of construct's positioning system! 
<img width="1059" alt="screen shot 2018-06-16 at 02 05 52" src="https://user-images.githubusercontent.com/3727889/41494340-d6682fb4-7109-11e8-807d-9facbd7b8bfa.png">

**Comment by organised** [comment]
resolved. will be updated in the next upload.
