### ISSUE TITLE
MASK COLOURS

### ISSUE THREAD

**Issue by adamgstudio** [organised/gkits#20]
If you have time, just a slight tweak:

Green: R16  G81  B74
Blue: R16   G70   B30
Red: R176   G17   B33

**Comment by organised** [comment]
<img width="472" alt="screen shot 2018-06-27 at 23 15 52" src="https://user-images.githubusercontent.com/3727889/42002761-4ecf4a6e-7a60-11e8-9977-ddf0ac2dbedc.png">
<img width="819" alt="screen shot 2018-06-27 at 23 14 48" src="https://user-images.githubusercontent.com/3727889/42002762-4eefced8-7a60-11e8-91dc-04d863cac7d6.png">
<img width="1079" alt="screen shot 2018-06-27 at 23 10 12" src="https://user-images.githubusercontent.com/3727889/42002763-4f096e42-7a60-11e8-960b-9347aea7c392.png">
<img width="1072" alt="screen shot 2018-06-27 at 23 10 05" src="https://user-images.githubusercontent.com/3727889/42002764-4f2484e8-7a60-11e8-8277-f5044956af1b.png">
the blue one is off a bit thats all, just let me know what your preferred values are.

**Comment by organised** [comment]
Blue was changed to 16,70,130
had to add these to the intial data loading too otherwise the share button coloured them incorrectly.
