### ISSUE TITLE
Titles/blocks/columns

### ISSUE THREAD

**Issue by adamgstudio** [organised/gkits#3]
Please ensure that the control panel content is confined to the width of each column - see my artwork for reference. I can see the dotted lines sticking out on right hand side of column 1, and the first letter of title text on left of colum 2 are hanging over. Minor thing but major, impact!

If in doubt - see my artwork to you. up-to-date version here:
https://www.dropbox.com/s/k8ionwacnm42nk8/GrammarKitsv4.pdf?dl=0

Thanks!

**Comment by organised** [comment]
yeah was ugly, those dots are not graphics, they're rendered full stops. so it's been pretty fiddly messing with them but I think it's very close to the desired parameters now. I've used a shimmy to measure layout visually or by numeric positioning where the origins lined up.  Closing this issue and if you spot any particular bits, please start a specific new one. 

<img width="1083" alt="screen shot 2018-06-16 at 21 38 29" src="https://user-images.githubusercontent.com/3727889/41502277-9091317a-71ae-11e8-9103-89a05fef0e0c.png">
