### ISSUE TITLE
Large buttons

### ISSUE THREAD

**Issue by adamgstudio** [organised/gkits#5]
Not keen on the stylign of these - the badge buttons have incorrect font/fotn size and is left-aligned, and the black buttons should be at bottom of page and also have incorrect font/fonts size/ and is left aligned. 

I will supply you a 'save' graphic so you can use a uniformed icon and match up to the share one.

Thanks

**Comment by organised** [comment]
fixed the internal alignment, fixed the inside graphic, 
fixed the page alignment.
font not fixed yet. 

(not published yet)
